name: khayata_app
description: تطبيق إدارة بيانات عملاء الخياطة
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  file_selector: ^1.0.3
  path_provider: ^2.1.2
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.1
  firebase_crashlytics: ^4.3.10
  cloud_firestore: ^5.5.1
  firebase_app_check: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf