// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnDDKwgEtE0CFHvAEJjMhD4Y4mFcoiokw',
    appId: '1:133640372158:web:c2c42dc4fffb70eed903ef',
    messagingSenderId: '133640372158',
    projectId: 'khayataapp2020',
    authDomain: 'khayataapp2020.firebaseapp.com',
    storageBucket: 'khayataapp2020.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdJgCvYD0WZynPFAxBoHgyAloy4n0VFYg',
    appId: '1:133640372158:android:e5b14c275d497a80d903ef',
    messagingSenderId: '133640372158',
    projectId: 'khayataapp2020',
    storageBucket: 'khayataapp2020.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPKQULlu6_1K26_bQ9TDipzvKRrxEmLus',
    appId: '1:133640372158:ios:28432ebcba81c70cd903ef',
    messagingSenderId: '133640372158',
    projectId: 'khayataapp2020',
    storageBucket: 'khayataapp2020.firebasestorage.app',
    iosBundleId: 'com.example.khayata2app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPKQULlu6_1K26_bQ9TDipzvKRrxEmLus',
    appId: '1:133640372158:ios:28432ebcba81c70cd903ef',
    messagingSenderId: '133640372158',
    projectId: 'khayataapp2020',
    storageBucket: 'khayataapp2020.firebasestorage.app',
    iosBundleId: 'com.example.khayata2app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnDDKwgEtE0CFHvAEJjMhD4Y4mFcoiokw',
    appId: '1:133640372158:web:a46d754812bfea82d903ef',
    messagingSenderId: '133640372158',
    projectId: 'khayataapp2020',
    authDomain: 'khayataapp2020.firebaseapp.com',
    storageBucket: 'khayataapp2020.firebasestorage.app',
  );
}
